version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  MVN: '{{if eq .GOOS "windows"}}mvn.cmd{{else}}mvn{{end}}'
  DC_DIR: "."
  INFRA_DC_FILE: "{{.DC_DIR}}/docker-compose.yml"
  APP_DC_FILE: "{{.DC_DIR}}/docker-compose-app.yml"
  MONITOR_DC_FILE: "{{.DC_DIR}}/docker-compose-monitor.yml"
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [ format ]
    cmds:
      - "{{.MVN}} clean verify"

  format:
    cmds:
      - "{{.MVN}} spotless:apply"

  build:
    cmds:
      - "{{.MVN}} -pl rose-microservice/rose-upms spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl rose-microservice/rose-xxljob spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl rose-microservice/rose-monitor spring-boot:build-image -DskipTests"
      - "{{.MVN}} -pl rose-microservice/rose-gateway spring-boot:build-image -DskipTests"

  start_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"

  stop_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} rm -f"

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  start_monitor:
    cmds:
      - "docker compose -f {{.MONITOR_DC_FILE}} up -d"

  stop_monitor:
    cmds:
      - "docker compose -f {{.MONITOR_DC_FILE}} stop"
      - "docker compose -f {{.MONITOR_DC_FILE}} rm -f"

  restart_monitor:
    cmds:
      - task: stop_monitor
      - task: sleep
      - task: start_monitor

  start:
    deps: [ build ]
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} up -d"

  stop:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APP_DC_FILE}} rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"
